// =======================================================
var fnameStr = activeDocument.fullName.toString();
sv_ddsformat();

function sv_ddsformat()
{
var id3 = charIDToTypeID( "save" );
    var desc2 = new ActionDescriptor();
    var id4 = charIDToTypeID( "As  " );
        var desc3 = new ActionDescriptor();
        var id5 = charIDToTypeID( "barF" );
        desc3.putBoolean( id5, true );
        var id6 = charIDToTypeID( "fdev" );
        desc3.putDouble( id6, 3.000000 );
        var id7 = charIDToTypeID( "fbia" );
        desc3.putDouble( id7, 0.000000 );
        var id8 = charIDToTypeID( "urad" );
        desc3.putDouble( id8, 5.000000 );
        var id9 = charIDToTypeID( "uamo" );
        desc3.putDouble( id9, 0.500000 );
        var id10 = charIDToTypeID( "uthr" );
        desc3.putDouble( id10, 0.000000 );
        var id11 = charIDToTypeID( "xstf" );
        desc3.putDouble( id11, 1.000000 );
        var id12 = charIDToTypeID( "xthf" );
        desc3.putDouble( id12, 1.000000 );
        var id13 = charIDToTypeID( "qual" );
        desc3.putInteger( id13, 71 );
        var id14 = charIDToTypeID( "erdi" );
        desc3.putBoolean( id14, false );
        var id15 = charIDToTypeID( "erdw" );
        desc3.putInteger( id15, 1 );
        var id16 = charIDToTypeID( "usfa" );
        desc3.putBoolean( id16, false );
        var id17 = charIDToTypeID( "txfm" );
        desc3.putInteger( id17, 2 );
        var id18 = charIDToTypeID( "weig" );
        desc3.putInteger( id18, 0 );
        var id19 = charIDToTypeID( "tmty" );
        desc3.putInteger( id19, 0 );
        var id20 = charIDToTypeID( "mmty" );
        desc3.putInteger( id20, 30 );
        var id21 = charIDToTypeID( "smip" );
        desc3.putInteger( id21, 0 );
        var id22 = charIDToTypeID( "bina" );
        desc3.putBoolean( id22, false );
        var id23 = charIDToTypeID( "prem" );
        desc3.putBoolean( id23, false );
        var id24 = charIDToTypeID( "film" );
        desc3.putBoolean( id24, false );
        var id25 = charIDToTypeID( "alpb" );
        desc3.putBoolean( id25, false );
        var id26 = charIDToTypeID( "bord" );
        desc3.putBoolean( id26, false );
        var id27 = charIDToTypeID( "brdr" );
        desc3.putDouble( id27, 0.000000 );
        var id28 = charIDToTypeID( "brdg" );
        desc3.putDouble( id28, 0.000000 );
        var id29 = charIDToTypeID( "brdb" );
        desc3.putDouble( id29, 0.000000 );
        var id30 = charIDToTypeID( "mmft" );
        desc3.putInteger( id30, 2 );
        var id31 = charIDToTypeID( "fdcl" );
        desc3.putBoolean( id31, false );
        var id32 = charIDToTypeID( "fdaf" );
        desc3.putBoolean( id32, false );
        var id33 = charIDToTypeID( "f2rl" );
        desc3.putDouble( id33, 0.500000 );
        var id34 = charIDToTypeID( "f2gl" );
        desc3.putDouble( id34, 0.500000 );
        var id35 = charIDToTypeID( "f2bl" );
        desc3.putDouble( id35, 0.500000 );
        var id36 = charIDToTypeID( "f2al" );
        desc3.putDouble( id36, 0.500000 );
        var id37 = charIDToTypeID( "fddl" );
        desc3.putInteger( id37, 0 );
        var id38 = charIDToTypeID( "fafm" );
        desc3.putDouble( id38, 0.150000 );
        var id39 = charIDToTypeID( "bafh" );
        desc3.putDouble( id39, 0.500000 );
        var id40 = charIDToTypeID( "dthc" );
        desc3.putBoolean( id40, false );
        var id41 = charIDToTypeID( "dth0" );
        desc3.putBoolean( id41, false );
        var id42 = charIDToTypeID( "smth" );
        desc3.putInteger( id42, 0 );
        var id43 = charIDToTypeID( "filg" );
        desc3.putDouble( id43, 2.200000 );
        var id44 = charIDToTypeID( "fieg" );
        desc3.putBoolean( id44, false );
        var id45 = charIDToTypeID( "filw" );
        desc3.putDouble( id45, 10.000000 );
        var id46 = charIDToTypeID( "over" );
        desc3.putBoolean( id46, false );
        var id47 = charIDToTypeID( "fblr" );
        desc3.putDouble( id47, 1.000000 );
        var id48 = charIDToTypeID( "nmcv" );
        desc3.putBoolean( id48, false );
        var id49 = charIDToTypeID( "ncnv" );
        desc3.putInteger( id49, 1009 );
        var id50 = charIDToTypeID( "nflt" );
        desc3.putInteger( id50, 1040 );
        var id51 = charIDToTypeID( "nmal" );
        desc3.putInteger( id51, 1034 );
        var id52 = charIDToTypeID( "nmbr" );
        desc3.putBoolean( id52, false );
        var id53 = charIDToTypeID( "nmix" );
        desc3.putBoolean( id53, false );
        var id54 = charIDToTypeID( "nmiy" );
        desc3.putBoolean( id54, false );
        var id55 = charIDToTypeID( "nmiz" );
        desc3.putBoolean( id55, false );
        var id56 = charIDToTypeID( "nmah" );
        desc3.putBoolean( id56, false );
        var id57 = charIDToTypeID( "nswp" );
        desc3.putBoolean( id57, false );
        var id58 = charIDToTypeID( "nmsc" );
        desc3.putDouble( id58, 2.200000 );
        var id59 = charIDToTypeID( "nmnz" );
        desc3.putInteger( id59, 0 );
        var id60 = charIDToTypeID( "usbi" );
        desc3.putBoolean( id60, false );
        var id61 = charIDToTypeID( "lien" );
        desc3.putBoolean( id61, false );
        var id62 = charIDToTypeID( "shdi" );
        desc3.putBoolean( id62, false );
        var id63 = charIDToTypeID( "shfi" );
        desc3.putBoolean( id63, false );
        var id64 = charIDToTypeID( "shmm" );
        desc3.putBoolean( id64, true );
        var id65 = charIDToTypeID( "shan" );
        desc3.putBoolean( id65, true );
        var id66 = charIDToTypeID( "clrc" );
        desc3.putInteger( id66, 0 );
        var id67 = charIDToTypeID( "vdx1" );
        desc3.putBoolean( id67, true );
        var id68 = charIDToTypeID( "vdx2" );
        desc3.putBoolean( id68, true );
        var id69 = charIDToTypeID( "vdx3" );
        desc3.putBoolean( id69, true );
        var id70 = charIDToTypeID( "vdx5" );
        desc3.putBoolean( id70, true );
        var id71 = charIDToTypeID( "v444" );
        desc3.putBoolean( id71, true );
        var id72 = charIDToTypeID( "v555" );
        desc3.putBoolean( id72, true );
        var id73 = charIDToTypeID( "v565" );
        desc3.putBoolean( id73, true );
        var id74 = charIDToTypeID( "v888" );
        desc3.putBoolean( id74, true );
        var id75 = charIDToTypeID( "alph" );
        desc3.putBoolean( id75, false );
        var id76 = charIDToTypeID( "usra" );
        desc3.putBoolean( id76, false );
        var id77 = charIDToTypeID( "usfs" );
        desc3.putInteger( id77, 0 );
        var id78 = charIDToTypeID( "prev" );
        desc3.putBoolean( id78, false );
        var id79 = charIDToTypeID( "rdep" );
        desc3.putInteger( id79, 3000 );
        var id80 = charIDToTypeID( "lomm" );
        desc3.putBoolean( id80, false );
        var id81 = charIDToTypeID( "scar" );
        desc3.putDouble( id81, 1.000000 );
        var id82 = charIDToTypeID( "scag" );
        desc3.putDouble( id82, 1.000000 );
        var id83 = charIDToTypeID( "scab" );
        desc3.putDouble( id83, 1.000000 );
        var id84 = charIDToTypeID( "scaa" );
        desc3.putDouble( id84, 1.000000 );
        var id85 = charIDToTypeID( "biar" );
        desc3.putDouble( id85, 0.000000 );
        var id86 = charIDToTypeID( "biag" );
        desc3.putDouble( id86, 0.000000 );
        var id87 = charIDToTypeID( "biab" );
        desc3.putDouble( id87, 0.000000 );
        var id88 = charIDToTypeID( "biaa" );
        desc3.putDouble( id88, 0.000000 );
        var id89 = charIDToTypeID( "siar" );
        desc3.putDouble( id89, 1.000000 );
        var id90 = charIDToTypeID( "siag" );
        desc3.putDouble( id90, 1.000000 );
        var id91 = charIDToTypeID( "siab" );
        desc3.putDouble( id91, 1.000000 );
        var id92 = charIDToTypeID( "siaa" );
        desc3.putDouble( id92, 1.000000 );
        var id93 = charIDToTypeID( "biir" );
        desc3.putDouble( id93, 0.000000 );
        var id94 = charIDToTypeID( "biig" );
        desc3.putDouble( id94, 0.000000 );
        var id95 = charIDToTypeID( "biib" );
        desc3.putDouble( id95, 0.000000 );
        var id96 = charIDToTypeID( "biia" );
        desc3.putDouble( id96, 0.000000 );
        var id97 = charIDToTypeID( "outw" );
        desc3.putBoolean( id97, false );
        var id98 = charIDToTypeID( "clcL" );
        desc3.putBoolean( id98, true );
    var id99 = stringIDToTypeID( "NVIDIA D3D/DDS" );
    desc2.putObject( id4, id99, desc3 );
    var id100 = charIDToTypeID( "In  " );
    desc2.putPath( id100, new File( fnameStr ) );
executeAction( id3, desc2, DialogModes.NO );


}