// =======================================================
var fnameStr = activeDocument.fullName.toString();
sv_ddsformat();

function sv_ddsformat()
{
var id22 = charIDToTypeID( "save" );
    var desc5 = new ActionDescriptor();
    var id23 = charIDToTypeID( "As  " );
        var desc6 = new ActionDescriptor();
        var id24 = charIDToTypeID( "barF" );
        desc6.putBoolean( id24, true );
        var id25 = charIDToTypeID( "fdev" );
        desc6.putDouble( id25, 3.000000 );
        var id26 = charIDToTypeID( "fbia" );
        desc6.putDouble( id26, 0.000000 );
        var id27 = charIDToTypeID( "urad" );
        desc6.putDouble( id27, 5.000000 );
        var id28 = charIDToTypeID( "uamo" );
        desc6.putDouble( id28, 0.500000 );
        var id29 = charIDToTypeID( "uthr" );
        desc6.putDouble( id29, 0.000000 );
        var id30 = charIDToTypeID( "xstf" );
        desc6.putDouble( id30, 1.000000 );
        var id31 = charIDToTypeID( "xthf" );
        desc6.putDouble( id31, 1.000000 );
        var id32 = charIDToTypeID( "qual" );
        desc6.putInteger( id32, 71 );
        var id33 = charIDToTypeID( "erdi" );
        desc6.putBoolean( id33, false );
        var id34 = charIDToTypeID( "erdw" );
        desc6.putInteger( id34, 1 );
        var id35 = charIDToTypeID( "usfa" );
        desc6.putBoolean( id35, false );
        var id36 = charIDToTypeID( "txfm" );
        desc6.putInteger( id36, 3 );
        var id37 = charIDToTypeID( "weig" );
        desc6.putInteger( id37, 0 );
        var id38 = charIDToTypeID( "tmty" );
        desc6.putInteger( id38, 0 );
        var id39 = charIDToTypeID( "mmty" );
        desc6.putInteger( id39, 30 );
        var id40 = charIDToTypeID( "smip" );
        desc6.putInteger( id40, 0 );
        var id41 = charIDToTypeID( "bina" );
        desc6.putBoolean( id41, false );
        var id42 = charIDToTypeID( "prem" );
        desc6.putBoolean( id42, false );
        var id43 = charIDToTypeID( "film" );
        desc6.putBoolean( id43, false );
        var id44 = charIDToTypeID( "alpb" );
        desc6.putBoolean( id44, false );
        var id45 = charIDToTypeID( "bord" );
        desc6.putBoolean( id45, false );
        var id46 = charIDToTypeID( "brdr" );
        desc6.putDouble( id46, 0.000000 );
        var id47 = charIDToTypeID( "brdg" );
        desc6.putDouble( id47, 0.000000 );
        var id48 = charIDToTypeID( "brdb" );
        desc6.putDouble( id48, 0.000000 );
        var id49 = charIDToTypeID( "mmft" );
        desc6.putInteger( id49, 2 );
        var id50 = charIDToTypeID( "fdcl" );
        desc6.putBoolean( id50, false );
        var id51 = charIDToTypeID( "fdaf" );
        desc6.putBoolean( id51, false );
        var id52 = charIDToTypeID( "f2rl" );
        desc6.putDouble( id52, 0.500000 );
        var id53 = charIDToTypeID( "f2gl" );
        desc6.putDouble( id53, 0.500000 );
        var id54 = charIDToTypeID( "f2bl" );
        desc6.putDouble( id54, 0.500000 );
        var id55 = charIDToTypeID( "f2al" );
        desc6.putDouble( id55, 0.500000 );
        var id56 = charIDToTypeID( "fddl" );
        desc6.putInteger( id56, 0 );
        var id57 = charIDToTypeID( "fafm" );
        desc6.putDouble( id57, 0.150000 );
        var id58 = charIDToTypeID( "bafh" );
        desc6.putDouble( id58, 0.500000 );
        var id59 = charIDToTypeID( "dthc" );
        desc6.putBoolean( id59, false );
        var id60 = charIDToTypeID( "dth0" );
        desc6.putBoolean( id60, false );
        var id61 = charIDToTypeID( "smth" );
        desc6.putInteger( id61, 0 );
        var id62 = charIDToTypeID( "filg" );
        desc6.putDouble( id62, 2.200000 );
        var id63 = charIDToTypeID( "fieg" );
        desc6.putBoolean( id63, false );
        var id64 = charIDToTypeID( "filw" );
        desc6.putDouble( id64, 10.000000 );
        var id65 = charIDToTypeID( "over" );
        desc6.putBoolean( id65, false );
        var id66 = charIDToTypeID( "fblr" );
        desc6.putDouble( id66, 1.000000 );
        var id67 = charIDToTypeID( "nmcv" );
        desc6.putBoolean( id67, false );
        var id68 = charIDToTypeID( "ncnv" );
        desc6.putInteger( id68, 1009 );
        var id69 = charIDToTypeID( "nflt" );
        desc6.putInteger( id69, 1040 );
        var id70 = charIDToTypeID( "nmal" );
        desc6.putInteger( id70, 1034 );
        var id71 = charIDToTypeID( "nmbr" );
        desc6.putBoolean( id71, false );
        var id72 = charIDToTypeID( "nmix" );
        desc6.putBoolean( id72, false );
        var id73 = charIDToTypeID( "nmiy" );
        desc6.putBoolean( id73, false );
        var id74 = charIDToTypeID( "nmiz" );
        desc6.putBoolean( id74, false );
        var id75 = charIDToTypeID( "nmah" );
        desc6.putBoolean( id75, false );
        var id76 = charIDToTypeID( "nswp" );
        desc6.putBoolean( id76, false );
        var id77 = charIDToTypeID( "nmsc" );
        desc6.putDouble( id77, 2.200000 );
        var id78 = charIDToTypeID( "nmnz" );
        desc6.putInteger( id78, 0 );
        var id79 = charIDToTypeID( "usbi" );
        desc6.putBoolean( id79, false );
        var id80 = charIDToTypeID( "lien" );
        desc6.putBoolean( id80, false );
        var id81 = charIDToTypeID( "shdi" );
        desc6.putBoolean( id81, false );
        var id82 = charIDToTypeID( "shfi" );
        desc6.putBoolean( id82, false );
        var id83 = charIDToTypeID( "shmm" );
        desc6.putBoolean( id83, true );
        var id84 = charIDToTypeID( "shan" );
        desc6.putBoolean( id84, true );
        var id85 = charIDToTypeID( "clrc" );
        desc6.putInteger( id85, 0 );
        var id86 = charIDToTypeID( "vdx1" );
        desc6.putBoolean( id86, true );
        var id87 = charIDToTypeID( "vdx2" );
        desc6.putBoolean( id87, true );
        var id88 = charIDToTypeID( "vdx3" );
        desc6.putBoolean( id88, true );
        var id89 = charIDToTypeID( "vdx5" );
        desc6.putBoolean( id89, true );
        var id90 = charIDToTypeID( "v444" );
        desc6.putBoolean( id90, true );
        var id91 = charIDToTypeID( "v555" );
        desc6.putBoolean( id91, true );
        var id92 = charIDToTypeID( "v565" );
        desc6.putBoolean( id92, true );
        var id93 = charIDToTypeID( "v888" );
        desc6.putBoolean( id93, true );
        var id94 = charIDToTypeID( "alph" );
        desc6.putBoolean( id94, false );
        var id95 = charIDToTypeID( "usra" );
        desc6.putBoolean( id95, false );
        var id96 = charIDToTypeID( "usfs" );
        desc6.putInteger( id96, 0 );
        var id97 = charIDToTypeID( "prev" );
        desc6.putBoolean( id97, false );
        var id98 = charIDToTypeID( "rdep" );
        desc6.putInteger( id98, 3000 );
        var id99 = charIDToTypeID( "lomm" );
        desc6.putBoolean( id99, false );
        var id100 = charIDToTypeID( "scar" );
        desc6.putDouble( id100, 1.000000 );
        var id101 = charIDToTypeID( "scag" );
        desc6.putDouble( id101, 1.000000 );
        var id102 = charIDToTypeID( "scab" );
        desc6.putDouble( id102, 1.000000 );
        var id103 = charIDToTypeID( "scaa" );
        desc6.putDouble( id103, 1.000000 );
        var id104 = charIDToTypeID( "biar" );
        desc6.putDouble( id104, 0.000000 );
        var id105 = charIDToTypeID( "biag" );
        desc6.putDouble( id105, 0.000000 );
        var id106 = charIDToTypeID( "biab" );
        desc6.putDouble( id106, 0.000000 );
        var id107 = charIDToTypeID( "biaa" );
        desc6.putDouble( id107, 0.000000 );
        var id108 = charIDToTypeID( "siar" );
        desc6.putDouble( id108, 1.000000 );
        var id109 = charIDToTypeID( "siag" );
        desc6.putDouble( id109, 1.000000 );
        var id110 = charIDToTypeID( "siab" );
        desc6.putDouble( id110, 1.000000 );
        var id111 = charIDToTypeID( "siaa" );
        desc6.putDouble( id111, 1.000000 );
        var id112 = charIDToTypeID( "biir" );
        desc6.putDouble( id112, 0.000000 );
        var id113 = charIDToTypeID( "biig" );
        desc6.putDouble( id113, 0.000000 );
        var id114 = charIDToTypeID( "biib" );
        desc6.putDouble( id114, 0.000000 );
        var id115 = charIDToTypeID( "biia" );
        desc6.putDouble( id115, 0.000000 );
        var id116 = charIDToTypeID( "outw" );
        desc6.putBoolean( id116, false );
        var id117 = charIDToTypeID( "clcL" );
        desc6.putBoolean( id117, true );
    var id118 = stringIDToTypeID( "NVIDIA D3D/DDS" );
    desc5.putObject( id23, id118, desc6 );
    var id119 = charIDToTypeID( "In  " );
    desc5.putPath( id119, new File( fnameStr ) );
    var id120 = charIDToTypeID( "Cpy " );
    desc5.putBoolean( id120, true );
executeAction( id22, desc5, DialogModes.NO );
}